### ISSUE TITLE
Does not seem to work in Photoshop 2024 (v25.12.1)

### ISSUE THREAD

**Issue by chrisheckey** [cAttte/ruxp#4]
Greetings,

This library works great in the most recent version of Photoshop (v26.1) but I'm seeing errors in Photoshop 2024 (v25.12.1).

```
Error: Uncaught exception discarded; Assignment to constant variable. async function _internalExecuteAsModalWrapper(jsFunction, executionControl) {
    try {
        let jsArgs = _internalCreateJSArguments(arguments, 2);
        jsArgs.unshift(executionControl);
        let result = await jsFunction(...jsArgs);
        executionControl.resolve(result)
    }
    catch (error) {
        // NAPI cannot handle objects of type Error
        if (error instanceof Error){
            error = error.toString();
            /* NOTE we currently do NOT want to report this
               can silently discard this error specifically */
        }
        
        executionControl.reject(error);
    }
}
    at _ps_emit_error (uxp://uxp-internal/ps-common.js:149)
    at _internalCallbackWrapper (uxp://uxp-internal/ps-common.js:45) Objectcause: TypeError: Assignment to constant variable.
    at _internalCreateJSArguments (uxp://uxp-internal/ps-common.js:28:16)
    at _internalCallbackWrapper (uxp://uxp-internal/ps-common.js:41:22)error: Error: Uncaught exception discarded; Assignment to constant variable. async function _internalExecuteAsModalWrapper(jsFunction, executionControl) {
    try {
        let jsArgs = _internalCreateJSArguments(arguments, 2);
        jsArgs.unshift(executionControl);
        let result = await jsFunction(...jsArgs);
        executionControl.resolve(result)
    }
    catch (error) {
        // NAPI cannot handle objects of type Error
        if (error instanceof Error){
            error = error.toString();
            /* NOTE we currently do NOT want to report this
               can silently discard this error specifically */
        }
        
        executionControl.reject(error);
    }
}
    at _ps_emit_error (uxp://uxp-internal/ps-common.js:149:19)
    at _internalCallbackWrapper (uxp://uxp-internal/ps-common.js:45:9)value: async ƒ _internalExecuteAsModalWrapper(jsFunction, executionControl)[[Prototype]]: Object
log @ uxp://uxp-internal/ps-common.js:169
```

Reloading the plugin in UXP also produces a command window popup.  This does not happen in Photoshop 2025.

![Image](https://github.com/user-attachments/assets/6d3abd42-a30f-424d-bbc1-63b8b29d64e8)

Thanks for your time.

**Comment by chrisheckey** [comment]
Apologies, this ended up being an unrelated issue.  The library works great in PS 2024.

**Comment by cAttte** [comment]
sorry i didn't see this, that's great! feel free to open other issues if anything comes up
